import { Service } from "@/types";

export const services: Service[] = [
  {
    title: "RAG Chatbot Development",
    slug: "rag-chatbot",
    shortDescription: "Intelligent chatbots powered by your data. RAG-based AI that answers accurately with citations.",
    fullDescription: "Transform your customer experience with Retrieval-Augmented Generation (RAG) chatbots that understand your business data. Our custom chatbots pull from your knowledge base, documentation, and databases to provide accurate, cited responses that never hallucinate. Perfect for customer support, internal knowledge bases, and expert systems.",
    icon: "MessageSquare",
    color: "from-violet-500 to-purple-600",
    features: [
      "Custom RAG pipeline with your data sources",
      "Vector database integration (Pinecone, Weaviate)",
      "Citation-backed responses with source links",
      "Multi-format document processing (PDF, DOC, TXT)",
      "Advanced semantic search capabilities",
      "Chat history and conversation memory",
      "Admin dashboard for analytics and insights",
      "API integration with existing platforms",
    ],
    benefits: [
      "90%+ accuracy with cited sources",
      "Reduce support tickets by up to 70%",
      "24/7 instant responses to customer queries",
      "Scale knowledge access across your organization",
    ],
    idealFor: "Companies with extensive documentation, knowledge bases, or product information that need accurate AI responses",
    deliverables: [
      "Custom RAG chatbot application",
      "Vector database setup and data ingestion",
      "Document processing pipeline",
      "Admin analytics dashboard",
      "Integration with your platforms",
      "Documentation and training",
    ],
    timeline: "4-8 weeks",
    startingPrice: "$15,000",
  },
  {
    title: "AI Agent Development",
    slug: "ai-agents",
    shortDescription: "Autonomous AI agents that work independently. Multi-step task automation with smart decision-making.",
    fullDescription: "Deploy intelligent AI agents that autonomously execute complex workflows, make decisions, and interact with your tools. From research agents to sales automation agents, we build AI systems that work 24/7 to amplify your team's productivity. Powered by advanced LLMs and custom tool integrations.",
    icon: "Bot",
    color: "from-cyan-500 to-blue-600",
    features: [
      "Autonomous multi-step task execution",
      "Custom tool and API integrations",
      "Smart decision-making with LLM reasoning",
      "Human-in-the-loop approval workflows",
      "Task queue and scheduling system",
      "Agent monitoring and logging",
      "Multi-agent collaboration systems",
      "Custom prompts and behavior tuning",
    ],
    benefits: [
      "Automate complex workflows end-to-end",
      "50+ hours saved per employee per week",
      "Scale operations without hiring",
      "Consistent execution with zero errors",
    ],
    idealFor: "Businesses looking to automate repetitive knowledge work, research tasks, or multi-step business processes",
    deliverables: [
      "Custom AI agent architecture",
      "Tool integration layer",
      "Agent orchestration system",
      "Monitoring and alerting dashboard",
      "Agent behavior documentation",
      "Training and handover sessions",
    ],
    timeline: "6-10 weeks",
    startingPrice: "$25,000",
  },
  {
    title: "AI Website Builder",
    slug: "ai-website",
    shortDescription: "Modern websites with built-in AI. Fast, SEO-optimized sites with integrated chatbots.",
    fullDescription: "Get a stunning, high-performance website built with the latest AI technologies. From SaaS landing pages to complete business websites, we create digital experiences that engage visitors, rank on Google, and drive conversions—all with built-in AI chatbot integration. Built on Next.js for optimal performance.",
    icon: "Globe",
    color: "from-emerald-500 to-teal-600",
    features: [
      "Custom Next.js website development",
      "AI chatbot integration from day one",
      "SEO-optimized architecture",
      "Lightning-fast page load speeds",
      "Mobile-first responsive design",
      "CMS integration for content management",
      "Analytics and conversion tracking",
      "Vercel deployment with CI/CD",
    ],
    benefits: [
      "Launch in weeks, not months",
      "Built-in AI capabilities out of the box",
      "95+ PageSpeed scores guaranteed",
      "SEO-ready for immediate ranking",
    ],
    idealFor: "Startups, SaaS companies, and businesses needing a modern web presence with AI capabilities",
    deliverables: [
      "Fully functional Next.js website",
      "Integrated AI chatbot",
      "CMS setup and content migration",
      "SEO optimization and sitemap",
      "Analytics and tracking setup",
      "Documentation and training",
    ],
    timeline: "4-8 weeks",
    startingPrice: "$12,000",
  },
  {
    title: "AI Landing Page Builder",
    slug: "ai-landing-page",
    shortDescription: "High-converting landing pages powered by AI. A/B tested, optimized for conversions.",
    fullDescription: "Launch high-converting landing pages that turn visitors into customers. We combine AI-powered copywriting, data-driven design, and conversion optimization to create landing pages that perform. Includes A/B testing integration, analytics, and continuous optimization based on real user data.",
    icon: "Layout",
    color: "from-orange-500 to-red-600",
    features: [
      "AI-optimized copywriting and headlines",
      "Conversion-focused design patterns",
      "A/B testing framework integration",
      "Heatmap and analytics setup",
      "Fast page load optimization",
      "Mobile-responsive layouts",
      "Lead capture and CRM integration",
      "Continuous optimization recommendations",
    ],
    benefits: [
      "2-3x higher conversion rates",
      "Launch campaigns in days, not weeks",
      "Data-driven design decisions",
      "Continuous performance improvement",
    ],
    idealFor: "Marketing teams, startups, and businesses running paid campaigns or product launches",
    deliverables: [
      "High-converting landing page design",
      "AI-generated copy and content",
      "A/B testing setup",
      "Analytics and tracking integration",
      "Lead capture and notification system",
      "Performance optimization report",
    ],
    timeline: "2-4 weeks",
    startingPrice: "$5,000",
  },
];

export const serviceCategories = [
  {
    name: "AI Chatbots & Agents",
    services: ["RAG Chatbot Development", "AI Agent Development"],
    description: "Intelligent automation that works 24/7.",
  },
  {
    name: "AI Websites & Landing Pages",
    services: ["AI Website Builder", "AI Landing Page Builder"],
    description: "Modern web experiences powered by AI.",
  },
];
